import { describe, expect, it } from 'vitest';
import golden from './__fixtures__/golden-solar-positions.json';
import { civilToInstant, seasonName, solarPosition } from './solar';
import { compassLabel, shadowReachM, sunDirectionENU } from './sun';

/*
 * The sun, checked against 36 samples generated by pvlib's NREL SPA
 * implementation (sunlight-twin/contracts/golden/solar_positions.json).
 *
 * This is the test that makes the shadows trustworthy. The three ways solar
 * geometry usually goes wrong — a northern-hemisphere azimuth convention, a
 * hard-coded UTC offset, and refraction mixed into a geometric figure — all
 * produce shadows that look entirely plausible on screen. None of them
 * survives a 0.1° comparison.
 */

interface GoldenSample {
  local: string;
  utc: string;
  utc_offset_hours: number;
  elevation_deg: number;
  azimuth_deg: number;
  apparent_elevation_deg: number;
}

const TOLERANCE_DEG = golden.conventions.tolerance_deg;
const site = {
  lat: golden.site.latitude,
  lon: golden.site.longitude,
  elevationM: golden.site.elevation_m,
};
const samples = golden.samples as GoldenSample[];

/** Smallest angle between two bearings, degrees. Handles the 0/360 seam. */
function bearingDelta(a: number, b: number): number {
  const diff = Math.abs(((a - b) % 360) + 360) % 360;
  return diff > 180 ? 360 - diff : diff;
}

describe('solar position against the pvlib golden vectors', () => {
  it('has 36 samples and a stated tolerance', () => {
    expect(samples).toHaveLength(36);
    expect(TOLERANCE_DEG).toBe(0.1);
  });

  it.each(samples.map((s, i) => [i, s] as const))(
    'sample %i matches within tolerance',
    (_i, sample) => {
      const { altitudeDeg, azimuthDeg } = solarPosition(new Date(sample.utc), site);
      expect(Math.abs(altitudeDeg - sample.elevation_deg)).toBeLessThanOrEqual(TOLERANCE_DEG);
      expect(bearingDelta(azimuthDeg, sample.azimuth_deg)).toBeLessThanOrEqual(TOLERANCE_DEG);
    },
  );

  it('is geometric, not refracted', () => {
    // Near the horizon the two differ by more than the tolerance. If this
    // ever passes against apparent_elevation_deg, refraction has crept in.
    const low = samples.reduce((a, b) => (a.elevation_deg < b.elevation_deg ? a : b));
    const gap = low.apparent_elevation_deg - low.elevation_deg;
    expect(gap).toBeGreaterThan(TOLERANCE_DEG * 0.5);

    const { altitudeDeg } = solarPosition(new Date(low.utc), site);
    expect(Math.abs(altitudeDeg - low.elevation_deg)).toBeLessThan(
      Math.abs(altitudeDeg - low.apparent_elevation_deg),
    );
  });
});

describe('southern-hemisphere behaviour', () => {
  it('puts the sun due north at transit, so shadows fall south', () => {
    const transit = golden.derived.solar_transit_local;
    const [date, time] = transit.split('T');
    const [y, m, d] = date.split('-').map(Number);
    const [hh, mm] = time.split(':').map(Number);

    const instant = civilToInstant(golden.site.timezone, y, m, d, hh, mm);
    const { altitudeDeg, azimuthDeg } = solarPosition(instant, site);

    expect(bearingDelta(azimuthDeg, 0)).toBeLessThan(0.5);
    expect(altitudeDeg).toBeCloseTo(golden.derived.transit_elevation_deg, 1);

    // Sun to the north means the light vector points north and up, so the
    // shadow it throws runs south.
    const direction = sunDirectionENU({ altitudeDeg, azimuthDeg });
    expect(direction.north).toBeGreaterThan(0.5);
    expect(direction.up).toBeGreaterThan(0);
    expect(Math.abs(direction.east)).toBeLessThan(0.05);
  });

  it('runs east in the morning and west in the afternoon', () => {
    const morning = samples[0];
    const afternoon = samples[samples.length - 1];
    expect(morning.azimuth_deg).toBeGreaterThan(0);
    expect(morning.azimuth_deg).toBeLessThan(90);
    expect(afternoon.azimuth_deg).toBeGreaterThan(270);
    expect(compassLabel(morning.azimuth_deg)).toBe('NORTH-EAST');
    expect(compassLabel(afternoon.azimuth_deg)).toBe('NORTH-WEST');
  });
});

describe('daylight saving is resolved from the zone, not assumed', () => {
  it('reads 21 June as UTC+10', () => {
    const instant = civilToInstant('Australia/Melbourne', 2026, 6, 21, 12, 0);
    expect(instant.toISOString()).toBe('2026-06-21T02:00:00.000Z');
  });

  it('reads 21 December as UTC+11', () => {
    // If this comes out as 13:00Z the offset has been hard-coded to +10 and
    // every summer shadow is an hour out.
    const instant = civilToInstant('Australia/Melbourne', 2026, 12, 21, 12, 0);
    expect(instant.toISOString()).toBe('2026-12-21T01:00:00.000Z');
  });

  it('agrees with the offset the golden file recorded', () => {
    for (const sample of samples) {
      const [date, time] = sample.local.split('T');
      const [y, m, d] = date.split('-').map(Number);
      const [hh, mm] = time.split(':').map(Number);
      const instant = civilToInstant(golden.site.timezone, y, m, d, hh, mm);
      expect(instant.toISOString()).toBe(sample.utc.replace('Z', '.000Z'));
      expect(sample.utc_offset_hours).toBe(10);
    }
  });
});

describe('shadow length', () => {
  it('lengthens as the sun drops', () => {
    const high = shadowReachM(214.1, 60)!;
    const low = shadowReachM(214.1, 5)!;
    expect(high).toBeLessThan(low);
    // 214 m at 5° reaches nearly 2.5 km — the case that used to be clipped
    // by the shadow frustum.
    expect(low).toBeGreaterThan(2400);
  });

  it('is undefined below the horizon', () => {
    expect(shadowReachM(100, 0)).toBeNull();
    expect(shadowReachM(100, -3)).toBeNull();
  });

  it('equals the height at 45 degrees', () => {
    expect(shadowReachM(100, 45)).toBeCloseTo(100, 6);
  });
});

describe('the season a month is in', () => {
  it('uses the southern hemisphere: December is summer and June is winter', () => {
    const names = Array.from({ length: 12 }, (_, i) => seasonName(i + 1));
    expect(names).toEqual([
      'Summer', 'Summer', 'Autumn', 'Autumn', 'Autumn', 'Winter',
      'Winter', 'Winter', 'Spring', 'Spring', 'Spring', 'Summer',
    ]);
  });
});
