/*
 * ─────────────────────────────────────────────────────────────────────────
 * THE MAP CREDENTIALS, FETCHED RATHER THAN BUILT IN
 * ─────────────────────────────────────────────────────────────────────────
 *
 * WHAT THIS FILE IS
 *   Where the Mapbox token and style come from. Not from the bundle: from a
 *   small file written next to it at deploy time and read at run time.
 *
 * WHY NOT `import.meta.env`, WHICH IS THE OBVIOUS WAY
 *
 *   A public token is meant to be readable — every site drawing a Mapbox map
 *   ships one, and what protects it is the URL restriction on it, not
 *   secrecy. But a token baked into the bundle is also baked into the
 *   RELEASE, and releases are committed. The host's secret scanning stops the
 *   push, and answering that by clicking "allow" once a term teaches
 *   everybody to click it, until the day it is hiding something real.
 *
 *   The second reason is the one that actually matters. A frozen release
 *   cannot be rebuilt — that is the whole point of freezing it. With the
 *   token inside, rotating the token silently kills the map on every version
 *   already submitted. Read from a file that deployment rewrites, ver-1 and
 *   ver-2 pick up the new token without being touched.
 *
 * WHY NOT PROXY IT THROUGH THE WORKER, WHICH WOULD HIDE IT ENTIRELY
 *   Because Mapbox forbids it: "All requests to Static Maps must be
 *   generated by an end-user device. If any requests are generated by a
 *   server, the resulting images cannot be later redistributed to end-user
 *   devices." The browser has to ask Mapbox directly, so the browser has to
 *   hold the token. The most that can be done is to keep it out of the
 *   repository, which is what this does.
 *
 * WHEN THE FILE IS NOT THERE
 *   Nothing happens, and nothing breaks. Anyone who clones this and runs it
 *   has no token, gets no file, and sees the city on plain ground — which is
 *   the same thing that happens when Mapbox is unreachable, and is handled
 *   in exactly the same place.
 */

import { useEffect, useState } from 'react';

/**
 * The one absolute path in the app, and the one place bundled() is wrong.
 *
 * Everything else a version ships lives inside that version and is addressed
 * through its base — see bundled.ts. This does not: which token the
 * deployment uses is a fact about the DEPLOYMENT, and writing it inside
 * /ver-1/ would mean a deploy reaching into a frozen release to change it.
 * A frozen release is the one thing that must not move.
 *
 * So it sits at the root, above every version, and all of them read the same
 * one. bundled.test.ts knows about this exception by name and holds it to
 * this single path.
 */
const CONFIG_URL = '/mapbox.json';

export interface MapboxConfig {
  readonly token: string;
  readonly style: string;
}

/** Overridden by the deployed file; this is what to draw if it says nothing. */
const DEFAULT_STYLE = 'mapbox/light-v11';

/*
 * One request for the whole page, however many components ask.
 *
 * Held as the promise rather than the result, so that two callers mounting in
 * the same tick share the flight instead of racing to start a second one.
 */
let inFlight: Promise<MapboxConfig | null> | null = null;

function loadConfig(): Promise<MapboxConfig | null> {
  inFlight ??= fetch(CONFIG_URL)
    .then((response) => (response.ok ? response.json() : null))
    .then((doc: { token?: unknown; style?: unknown } | null) => {
      if (!doc || typeof doc.token !== 'string' || !doc.token) return null;
      return {
        token: doc.token,
        style: typeof doc.style === 'string' && doc.style ? doc.style : DEFAULT_STYLE,
      };
    })
    .catch(() => null);
  return inFlight;
}

export function useMapboxConfig(): MapboxConfig | null {
  const [config, setConfig] = useState<MapboxConfig | null>(null);

  useEffect(() => {
    let live = true;
    void loadConfig().then((result) => {
      if (live) setConfig(result);
    });
    return () => {
      live = false;
    };
  }, []);

  return config;
}
